# Generated by Django 5.1.5 on 2025-02-20 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taches', '0002_rename_titre_tache_nom_remove_projet_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='assigne_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
