# Generated by Django 5.1.5 on 2025-02-20 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taches', '0003_alter_tache_assigne_a'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
