# Generated by Django 5.1.5 on 2025-02-20 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taches', '0004_delete_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='taches.projet'),
        ),
    ]
